import AiSourceBadge from "./AiSourceBadge";
import DiffViewer from "./DiffViewer";
import { STATUS_LABEL, statusClass } from "../utils/fileStatus";
import { useExpandableSet } from "../hooks/useExpandableSet";

function SummaryBadge({ file }) {
  return <AiSourceBadge source={file.summarySource} provider={file.summaryProvider} />;
}

export default function FileWalkthrough({ files, aiProvider, prHtmlUrl }) {
  const { openKeys, toggle, expandAll, collapseAll } = useExpandableSet(
    files?.slice(0, 2).map((f) => f.filename) ?? []
  );
  const expandAllActive = files?.length > 0 && openKeys.size === files.length;

  if (!files?.length) {
    return <p className="muted">No file changes found.</p>;
  }

  const totalAdd = files.reduce((s, f) => s + (f.additions || 0), 0);
  const totalDel = files.reduce((s, f) => s + (f.deletions || 0), 0);
  const aiCount = files.filter((f) => f.summarySource === "ai").length;

  const handleExpandAll = () => {
    if (expandAllActive) collapseAll();
    else expandAll(files.map((f) => f.filename));
  };

  return (
    <div className="walkthrough">
      <div className="walkthrough-toolbar">
        <span className="muted">
          {files.length} files · <span className="diff-stat-add">+{totalAdd}</span>{" "}
          <span className="diff-stat-del">-{totalDel}</span>
          {aiCount > 0 && aiProvider && (
            <> · <span className="summary-badge summary-badge-ai">{aiCount} {aiProvider} summaries</span></>
          )}
        </span>
        <button type="button" className="btn ghost btn-sm" onClick={handleExpandAll}>
          {expandAllActive ? "Collapse all" : "Expand all"}
        </button>
      </div>

      <p className="muted walkthrough-note">
        Summaries are generated by {aiProvider || "AI"} when you click <strong>Re-analyze</strong>. Refreshing the page shows the cached report.
      </p>

      <div className="file-list">
        {files.map((file) => {
          const isOpen = openKeys.has(file.filename);
          const providerLabel = file.summaryProvider || aiProvider || "AI";
          return (
            <div key={file.filename} className={`file-card ${isOpen ? "open" : ""}`}>
              <button type="button" className="file-card-header" onClick={() => toggle(file.filename)}>
                <span className={statusClass(file.status)}>{STATUS_LABEL[file.status] || "M"}</span>
                <span className="file-name">{file.filename}</span>
                <span className="file-stats">
                  {file.additions > 0 && <span className="diff-stat-add">+{file.additions}</span>}
                  {file.deletions > 0 && <span className="diff-stat-del">-{file.deletions}</span>}
                </span>
                <span className="file-chevron">{isOpen ? "▾" : "▸"}</span>
              </button>

              {isOpen && (
                <div className="file-card-body">
                  <div className="file-summary-row">
                    <SummaryBadge file={file} />
                  </div>
                  <p className="file-summary">{file.summary}</p>
                  {file.summarizedAt && (
                    <p className="muted file-summarized-at">
                      {providerLabel} summary saved {new Date(file.summarizedAt).toLocaleString()}
                    </p>
                  )}
                  <DiffViewer
                    patch={file.patch}
                    githubUrl={prHtmlUrl ? `${prHtmlUrl}/files` : undefined}
                    defaultExpanded
                  />
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
