import type { AnalysisReport, Severity } from "@codelens/analyzers";

const RISK_EMOJI: Record<Severity, string> = {
  high: "🔴",
  medium: "🟡",
  low: "🟢",
  info: "ℹ️",
};

export function renderMarkdownReport(report: AnalysisReport, reportUrl?: string): string {
  const lines: string[] = [
    "## 🔍 CodeLens PR Brief",
    "",
    `${RISK_EMOJI[report.riskLevel]} **Risk: ${report.riskLevel.toUpperCase()}** (${report.riskScore}/100)`,
    "",
    report.executiveSummary,
    "",
  ];

  if (report.focusAreas.length > 0) {
    lines.push("### Where to focus first", "");
    for (const area of report.focusAreas) {
      const files = area.files.length > 0 ? ` — \`${area.files.join("`, `")}\`` : "";
      lines.push(`${area.rank}. **${area.area}** (${area.severity}) — ${area.reason}${files}`);
    }
    lines.push("");
  }

  lines.push("### Analysis breakdown", "");
  for (const dim of report.dimensions) {
    const icon = dim.score >= 55 ? "⚠️" : dim.score >= 25 ? "📋" : "✅";
    lines.push(`<details><summary>${icon} ${dim.name} — ${dim.summary}</summary>`, "");
    if (dim.findings.length === 0) {
      lines.push("_No findings._", "");
    } else {
      for (const f of dim.findings.slice(0, 8)) {
        const loc = f.evidence.file ? ` (\`${f.evidence.file}\`)` : "";
        lines.push(`- **[${f.severity}]** ${f.title}${loc}: ${f.description}`);
      }
      lines.push("");
    }
    lines.push("</details>", "");
  }

  lines.push(
    "---",
    `<sub>Generated by CodeLens • ${new Date(report.generatedAt).toLocaleString()}${reportUrl ? ` • [Full report](${reportUrl})` : ""}</sub>`
  );

  return lines.join("\n");
}

export function renderCheckSummary(report: AnalysisReport): string {
  return `CodeLens: ${report.riskLevel.toUpperCase()} risk (${report.riskScore}/100) — ${report.focusAreas[0]?.area ?? "review changed files"}`;
}
