apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codelens-db
  namespace: codelens
  labels:
    app.kubernetes.io/name: codelens
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
